### ISSUE TITLE
Explanation/Algorithm for combinations/solution.py problem

### ISSUE THREAD

**Issue by riyaz-ali** [Ch1pStar/Foobar#1]
Hey @Ch1pStar, can you please provide an explanation for the solution in combinations/solution.py? I spent my whole day trying to solve the puzzle using Integer partition, Distinct Part partitions (I guess I was wrong ;) ), and ended up looking on ur solution but can't figure how this works......so can you please explain or provide a link to some related topic.
TIA

**Comment by Ch1pStar** [comment]
Hello @riyaz-ali,
The algorithm for diving an integer into distinct parts is implemented in most mathematical languages/programs. You can look here for example http://mathworld.wolfram.com/PartitionFunctionQ.html.
Maxima also has this function and is open source.

**Comment by riyaz-ali** [comment]
So this means that the `divsum` function in the code is an implementation of this [mathematical function](https://archive.lib.msu.edu/crcmath/math/math/p/p1_794.gif)

P.S. sorry for such silly questions but I am not from a mathematical background, so having a hard time understanding the problem..... just curious about how your works 😃

**Comment by sushifish** [comment]
The `divsum` function simply provides the summation of divisors for number x using the [Divisor Function](http://mathworld.wolfram.com/DivisorFunction.html).
This encompasses the first while loop and pretty self explanatory, provides the sum of the divisors. As an example using 36, we find the factors of 36 (2^2 and 3^2). For even factors we use the equation 2^3 - 1, simply increasing the power by 1 and subtracting 1. For odd factors we use (3^3 - 1) / 2, doing the same as the even numbers but dividing the result by 2. Then just multiply the results together and it returns the sum of all divisors

2^3 - 1 = 7 and (3^3 - 1) / 2 = 13
7 * 13 = 91

36's divisors are 1 + 2 + 3 + 4 + 6 + 9 + 12 + 18 + 36 = 91

This Divisor Function is being used as part of the [Odd Divisor Function](http://mathworld.wolfram.com/OddDivisorFunction.html).
This encompasses the second while loop and is returning all the odd divisors for all even numbers. Using 36 again where the sum of divisors is 91 and we want the sum of odd divisors. We do this by finding the sum of even divisors using the half of 36.

18 has the divisors 1 + 2 + 3 + 6 + 9 + 18 = 39
If we double 18's divisors they become all even numbers. 2 + 4 + 6 + 12 + 18 + 36 = 78, which corresponds directly to all of 36's even divisors. So we reduce the sum of 91 - 78 = 13 which is 36's sum of odd divisors.

This sum of odd divisors is used not in the standard generating function for [Partition Function Q](http://mathworld.wolfram.com/PartitionFunctionQ.html) but in one of the [recurrence relations](http://mathworld.wolfram.com/images/equations/PartitionFunctionQ/NumberedEquation2.gif) (located directly below the generating function on the page). The section of the function in brackets is the odd divisor function and the only thing we have left to do in this function is sum our divisor value * the total partitions for the previous numbers divided by our number where total partitions for numbers 0 and 1 = 1

This would look something like this to find total partition for number 4:
4 has odd divisor sum of 1
3 has odd divisor sum of 4 and has 2 unique partitions (3 and 1 + 2)
2 has odd divisor sum of 1 and has 1 unique partition (2)
1 and 0 are defined being 1 for both

((1 * 2) + (1 * 1) + (4 * 1) + (1 * 1)) / 4 = 2

So 4 has 2 unique partitions (1 + 3 and 4) The remaining non-unique partitions are (2 + 2 and 1 + 1 + 2 and 1 + 1 + 1 + 1) .

The last thing that happens is it subtracts 1 from the unique partitions because the requirements state it has to be at least 2 steps.
